config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:show, :new, :create, :destroy] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_presence_of :movie, :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie_id,  { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates_presence_of :overview
  validates :title, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates_presence_of :comment, :rating
  RATING = [0, 1, 2, 3, 4, 5]
  validates :rating, inclusion: { in: RATING }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)

    @bookmark.list = @list

    if @bookmark.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.delete

    redirect_to @bookmark.list
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.where(list: @list)
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.delete

    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)

    @review.list = @list

    if @review.save
      redirect_to @list
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="fontawesome-stars.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="navbar-brand">
        <%= image_tag "https://img.flaticon.com/icons/png/512/864/864818.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF" %>
      </div>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "My lists", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New list", new_list_path, class: "nav-link" %>
          </li>

        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
  </html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80);">
  <div class="container">
    <h1 class="text-center">Save any kind of movies</h1>
  </div>
</div>


<div class="container mt-5 mb-5">
  <h1>My Lists</h1>
  <div class="row d-flex justify-content-between">
    <% @lists.each do |list| %>
      <div class="col-4">
        <%= link_to list do %>
          <% if list.photo.attached? %>
            <div class="card-category mt-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key, height: 300, crop: :fill %>)">
            <%= list.name %>
          </div>
          <% else %>
          <div class="card-category mt-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80')">
            <%= list.name.capitalize %>
          </div>
          <% end %>
          <%#= link_to 'delete', list_path(list), method: 'delete', class: "delete_link" %>
        <% end %>
      </div>
    <% end %>
  </div>


      <%= link_to 'Create a movie list', new_list_path, class: "btn btn-primary mt-3" %>
</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80');">
</div>

<div class="container mt-5 mb-5">
  <h1>Create your new movie list</h1>
  <%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary mb-5" %>
  <% end %>

  <%= link_to 'back', root_path %>
</div>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>);">
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80');">
<% end %>
    <div class="container">
      <h1 class="text-center"><%= @list.name %></h1>
    </div>
  </div>

<div class="container mt-5 mb-5">
  <div class="row justify-content-between">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-4">
        <div class="card " style="width: 18rem;">
          <% if @list.photo.attached? %>
            <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80" alt="">
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title.capitalize %> • <%= @review.rating %></h5>
          <p class="card-text"><%= bookmark.comment %></p>
          <%= link_to 'delete', bookmark_path(bookmark), method: 'delete', class: "delete_link" %>
        </div>
      </div>
    <% end %> <br>
  </div>

  <div class="border-top">
    <h2 class="mt-3">Add a bookmark</h2>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie, input_html: { class: 'select2' } %>
      <%= f.submit %>
    <% end %>
  </div>

  <div class="border-top mt-3">
    <div class="row d-flex justify-content-between">
      <div class="col-6">
        <div class="mt-4">
          <h2>Reviews</h2>
          <ul class="list-group list-group-flush">
            <% @list.reviews.each do |review| %>
              <li class="list-group-item p-0 review">
                <% review.rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %> <br>
                <h5><%= review.comment %>
                </h5>
              </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-6">
        <div id="review_form" class="mt-4">
          <h2>Add your review</h2>
          <%= simple_form_for [@list, @review] do |f| %>
              <%= f.input :comment %>
              <div class="form-group">
                <fieldset class="rating">
                  <%=f.radio_button :rating, 5, :id => "star5" %><label for="star5" title="Excellent!">5 Stars</label>
                  <%=f.radio_button :rating, 4, :id => "star4" %> <label for="star4" title="Good!">4 Stars</label>
                  <%=f.radio_button :rating, 3, :id => "star3" %> <label for="star3" title="Average!">3 Stars</label>
                  <%=f.radio_button :rating, 2, :id => "star2" %> <label for="star2" title="Poor!">2 Stars</label>
                  <%=f.radio_button :rating, 1, :id => "star1" %> <label for="star1" title="Very Poor!">1 Stars</label>
                </fieldset>
                <%=f.submit class: "btn btn-success text-white"%>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <%= link_to 'back', root_path, class: "btn btn-primary mt-3" %>


</div>